name: client
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  fluttertoast: ^8.2.2
  google_maps_flutter: ^2.4.0
  geolocator: ^11.0.0
  image_picker: ^1.0.4
  http_parser: ^4.0.2
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.3.1
  fl_chart: ^1.0.0
  syncfusion_flutter_maps: ^29.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
